### PR TITLE
Create feb-15.md

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by xtuc** [comment]
Please indicate your availabilities on https://doodle.com/poll/myg5peqciwnbyiuy.

**If this is the first time** you are attending please send me your email address or username on Slack.

**Comment by hzoo** [comment]
My suggestions on what to talk about:

- Future of OpenCollective and more formal process
- Babel 7 Release and what we are doing about it
  - babelrc/node_modules lookup
  - new website docs with v7
  - upgrade tool
- Summer of Code
- longer term extra: can we kill the babylon codebase and switch to being a wrapper for acorn and or cherow? As long as either can output estree/babel ast we are good and we can implement the extras as plugins or wrap errors, etc. Personally I'd like to not maintain it if we are doing the same thing, and it grows the team in a way although of course that means we need to collaborate (which I want to do).

**Comment by xtuc** [comment]
We can discuss about https://github.com/babel/notes/issues/57 also

**Comment by xtuc** [comment]
It seems to be a good idea to merge https://github.com/babel/website/pull/1518 soon and get some early feedback. Let's discuss about it during the meeting!

**Pull request merged**
